services:
  db:
    image: postgres
    shm_size: 2gb
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2048M
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  pgdata:
