import pg

# One-off script for adding subreddits to the subreddit_groups table

groups = {
    "Sport": [
        "formula1",
        "nba",
        "Boxing",
        "baseball",
        "tennis",
        "LiverpoolFC",
        "49ers",
        "SquaredCircle",
        "suns",
        "bostonceltics",
        "sixers",
        "Cricket",
        "sports",
        "MkeBucks",
        "nbadiscussion",
        "fantasyfootball",
        "nyjets",
        "MTB",
        "coys",
        "warriors",
    ],
    "Gaming": [
        "wow",
        "Eve",
        "xboxone",
        "GlobalOffensive",
        "classicwow",
        "leagueoflegends",
        "StardewValley",
        "pokemongo",
        "skyrim",
        "RocketLeague",
        "Competitiveoverwatch",
        "RimWorld",
        "Brawlstars",
        "Rainbow6",
        "Steam",
        "eu4",
        "smashbros",
        "battlestations",
        "dndnext",
        "DestinyTheGame",
    ],
    "Nyheter": [
        "UpliftingNews",
        "savedyouaclick",
        "olympics",
        "gamernews",
        "offbeat",
        "technews",
        "news",
        "worldnews",
        "nottheonion",
    ],
    "Memes": [
        "Memes",
        "Tinder",
        "me_irl",
        "AdviceAnimals",
        "tumblr",
        "2meirl4meirl",
        "ComedyCemetry",
        "MemeEconomy",
        "bonehurtingjuice",
        "HistoryMemes",
        "BlackPeopleTwitter",
        "FellowKids",
        "starterpacks",
        "wholesomememes",
        "meirl",
        "BikiniBottomTwitter",
        "terriblefacebookmemes",
        "trashy",
    ],
    "Teknologi": [
        "Technology",
        "gadgets",
        "apple",
        "GooglePixel",
        "cscareerquestions",
        "Android",
        "Amd",
        "engineering",
        "computers",
        "Machinists",
        "battlestations",
        "MachineLearning",
        "headphones",
        "virtualreality",
        "linuxmasterrace",
        "cordcutters",
        "PowerShell",
        "arduino",
        "homelab",
        "csharp",
    ],
    "Friluftsliv": [
        "NatureIsFuckingLit",
        "camping",
        "Outdoors",
        "backpacking",
        "CampingandHiking",
        "skiing",
        "Bushcraft",
        "foraging",
        "darksky",
        "Ultralight",
        "vandwellers",
        "trainmeals",
        "myog",
        "natureporn",
        "WildernessBackpacking",
        "gopro",
        "CampingGear",
        "MostBeautiful",
        "climbing",
        "snowboarding",
    ],
    "Naturvitenskap": [
        "Environment",
        "science",
        "EverythingScience",
        "askscience",
        "EngineeringPorn",
        "Physics",
        "chemistry",
        "nasa",
        "elonmusk",
        "spacex",
        "linguistics",
        "physicgifs",
        "mycology",
        "conlangs",
        "astrophotography",
        "SampleSize",
        "Genealogy",
        "SpaceXLounge",
        "shittyrobots",
        "chemicalreactiongift",
    ],
    "Relasjoner": [
        "Tinder",
        "wedding",
        "internetparents",
        "truechildfree",
        "Frat",
        "AsianParentStories",
        "Adoption",
        "clothdiaps",
        "waiting_to_try",
        "TFABChartStalkers",
        "love",
        "narcissisticparents",
        "Mediums",
        "Mommit",
        "penpals",
        "AskParents",
        "AncestryDNA",
        "family",
        "relationship_advice",
        "dating_advice",
    ],
    "Bøker og skriving": [
        "comicbooks",
        "worldbuilding",
        "nosleep",
        "writing",
        "bookclub",
        "creepypasta",
        "suggestmeabook",
        "shortscarystories",
        "etymology",
        "Screenwriting",
        "booksuggestion",
        "books",
    ],
    "Helse og fitness": [
        "bodybuilding",
        "GetMotivated",
        "caming",
        "intermittentfasting",
        "HealthyFood",
        "bodyweightfitness",
        "fasting",
        "nutrition",
        "xxfitness",
        "bjj",
        "backpacking",
        "CampingandHiking",
        "skiing",
        "MuayThai",
        "keto",
        "weightlifting",
        "leangains",
        "fitbit",
        "swoleacceptance",
        "Supplements",
    ],
    "Wholesome": [
        "UpliftingNews",
        "MadeMeSmile",
        "Eyebleach",
        "dadjokes",
        "wholesomegifs",
        "UnexpectedlyWholesome",
        "HumanPorn",
        "MomForAMinute",
        "WholesomeComics",
        "happycrowds",
        "MostBeautiful",
        "happycowgifs",
        "whatcouldgoright",
        "wholesomegreentext",
        "ContagiousLaughter",
        "wholesomememes",
    ],
}

db = pg.Connector()
db.cursor.execute("DROP TABLE IF EXISTS subreddit_groups;")
db.cursor.execute("CREATE TABLE subreddit_groups (group_name TEXT, subreddit TEXT);")

for key in groups:
    for subreddit in groups[key]:
        query = f"INSERT INTO subreddit_groups (group_name, subreddit) VALUES ('{key}', '{subreddit}');"
        db.cursor.execute(query)
db.connection.commit()
